# Generated by Django 6.0.4 on 2026-05-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("http_client", "0002_requestrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestnode",
            name="pre_request_script",
            field=models.TextField(blank=True, default=""),
        ),
    ]
