# Generated by Django 6.0.4 on 2026-05-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("http_client", "0003_requestnode_pre_request_script"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestnode",
            name="test_script",
            field=models.TextField(blank=True, default=""),
        ),
    ]
