/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YoutubeDownloaderIndexRouteImport } from './routes/youtube-downloader/index'
import { Route as TextTranslatorIndexRouteImport } from './routes/text-translator/index'
import { Route as SrtTranslatorIndexRouteImport } from './routes/srt-translator/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as PersonalHubIndexRouteImport } from './routes/personal-hub/index'
import { Route as HttpClientIndexRouteImport } from './routes/http-client/index'
import { Route as DocxTranslatorIndexRouteImport } from './routes/docx-translator/index'
import { Route as DevToolsIndexRouteImport } from './routes/dev-tools/index'
import { Route as AudioTranscriberIndexRouteImport } from './routes/audio-transcriber/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeDownloaderIndexRoute = YoutubeDownloaderIndexRouteImport.update({
  id: '/youtube-downloader/',
  path: '/youtube-downloader/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextTranslatorIndexRoute = TextTranslatorIndexRouteImport.update({
  id: '/text-translator/',
  path: '/text-translator/',
  getParentRoute: () => rootRouteImport,
} as any)
const SrtTranslatorIndexRoute = SrtTranslatorIndexRouteImport.update({
  id: '/srt-translator/',
  path: '/srt-translator/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalHubIndexRoute = PersonalHubIndexRouteImport.update({
  id: '/personal-hub/',
  path: '/personal-hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpClientIndexRoute = HttpClientIndexRouteImport.update({
  id: '/http-client/',
  path: '/http-client/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocxTranslatorIndexRoute = DocxTranslatorIndexRouteImport.update({
  id: '/docx-translator/',
  path: '/docx-translator/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsIndexRoute = DevToolsIndexRouteImport.update({
  id: '/dev-tools/',
  path: '/dev-tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioTranscriberIndexRoute = AudioTranscriberIndexRouteImport.update({
  id: '/audio-transcriber/',
  path: '/audio-transcriber/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio-transcriber/': typeof AudioTranscriberIndexRoute
  '/dev-tools/': typeof DevToolsIndexRoute
  '/docx-translator/': typeof DocxTranslatorIndexRoute
  '/http-client/': typeof HttpClientIndexRoute
  '/personal-hub/': typeof PersonalHubIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/srt-translator/': typeof SrtTranslatorIndexRoute
  '/text-translator/': typeof TextTranslatorIndexRoute
  '/youtube-downloader/': typeof YoutubeDownloaderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio-transcriber': typeof AudioTranscriberIndexRoute
  '/dev-tools': typeof DevToolsIndexRoute
  '/docx-translator': typeof DocxTranslatorIndexRoute
  '/http-client': typeof HttpClientIndexRoute
  '/personal-hub': typeof PersonalHubIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/srt-translator': typeof SrtTranslatorIndexRoute
  '/text-translator': typeof TextTranslatorIndexRoute
  '/youtube-downloader': typeof YoutubeDownloaderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio-transcriber/': typeof AudioTranscriberIndexRoute
  '/dev-tools/': typeof DevToolsIndexRoute
  '/docx-translator/': typeof DocxTranslatorIndexRoute
  '/http-client/': typeof HttpClientIndexRoute
  '/personal-hub/': typeof PersonalHubIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/srt-translator/': typeof SrtTranslatorIndexRoute
  '/text-translator/': typeof TextTranslatorIndexRoute
  '/youtube-downloader/': typeof YoutubeDownloaderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio-transcriber/'
    | '/dev-tools/'
    | '/docx-translator/'
    | '/http-client/'
    | '/personal-hub/'
    | '/skills/'
    | '/srt-translator/'
    | '/text-translator/'
    | '/youtube-downloader/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audio-transcriber'
    | '/dev-tools'
    | '/docx-translator'
    | '/http-client'
    | '/personal-hub'
    | '/skills'
    | '/srt-translator'
    | '/text-translator'
    | '/youtube-downloader'
  id:
    | '__root__'
    | '/'
    | '/audio-transcriber/'
    | '/dev-tools/'
    | '/docx-translator/'
    | '/http-client/'
    | '/personal-hub/'
    | '/skills/'
    | '/srt-translator/'
    | '/text-translator/'
    | '/youtube-downloader/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioTranscriberIndexRoute: typeof AudioTranscriberIndexRoute
  DevToolsIndexRoute: typeof DevToolsIndexRoute
  DocxTranslatorIndexRoute: typeof DocxTranslatorIndexRoute
  HttpClientIndexRoute: typeof HttpClientIndexRoute
  PersonalHubIndexRoute: typeof PersonalHubIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  SrtTranslatorIndexRoute: typeof SrtTranslatorIndexRoute
  TextTranslatorIndexRoute: typeof TextTranslatorIndexRoute
  YoutubeDownloaderIndexRoute: typeof YoutubeDownloaderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube-downloader/': {
      id: '/youtube-downloader/'
      path: '/youtube-downloader'
      fullPath: '/youtube-downloader/'
      preLoaderRoute: typeof YoutubeDownloaderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-translator/': {
      id: '/text-translator/'
      path: '/text-translator'
      fullPath: '/text-translator/'
      preLoaderRoute: typeof TextTranslatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/srt-translator/': {
      id: '/srt-translator/'
      path: '/srt-translator'
      fullPath: '/srt-translator/'
      preLoaderRoute: typeof SrtTranslatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-hub/': {
      id: '/personal-hub/'
      path: '/personal-hub'
      fullPath: '/personal-hub/'
      preLoaderRoute: typeof PersonalHubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/http-client/': {
      id: '/http-client/'
      path: '/http-client'
      fullPath: '/http-client/'
      preLoaderRoute: typeof HttpClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docx-translator/': {
      id: '/docx-translator/'
      path: '/docx-translator'
      fullPath: '/docx-translator/'
      preLoaderRoute: typeof DocxTranslatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/': {
      id: '/dev-tools/'
      path: '/dev-tools'
      fullPath: '/dev-tools/'
      preLoaderRoute: typeof DevToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-transcriber/': {
      id: '/audio-transcriber/'
      path: '/audio-transcriber'
      fullPath: '/audio-transcriber/'
      preLoaderRoute: typeof AudioTranscriberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioTranscriberIndexRoute: AudioTranscriberIndexRoute,
  DevToolsIndexRoute: DevToolsIndexRoute,
  DocxTranslatorIndexRoute: DocxTranslatorIndexRoute,
  HttpClientIndexRoute: HttpClientIndexRoute,
  PersonalHubIndexRoute: PersonalHubIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  SrtTranslatorIndexRoute: SrtTranslatorIndexRoute,
  TextTranslatorIndexRoute: TextTranslatorIndexRoute,
  YoutubeDownloaderIndexRoute: YoutubeDownloaderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
