/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TextTranslatorIndexRouteImport } from './routes/text-translator/index'
import { Route as DocxTranslatorIndexRouteImport } from './routes/docx-translator/index'
import { Route as DevToolsIndexRouteImport } from './routes/dev-tools/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextTranslatorIndexRoute = TextTranslatorIndexRouteImport.update({
  id: '/text-translator/',
  path: '/text-translator/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocxTranslatorIndexRoute = DocxTranslatorIndexRouteImport.update({
  id: '/docx-translator/',
  path: '/docx-translator/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevToolsIndexRoute = DevToolsIndexRouteImport.update({
  id: '/dev-tools/',
  path: '/dev-tools/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev-tools/': typeof DevToolsIndexRoute
  '/docx-translator/': typeof DocxTranslatorIndexRoute
  '/text-translator/': typeof TextTranslatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev-tools': typeof DevToolsIndexRoute
  '/docx-translator': typeof DocxTranslatorIndexRoute
  '/text-translator': typeof TextTranslatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev-tools/': typeof DevToolsIndexRoute
  '/docx-translator/': typeof DocxTranslatorIndexRoute
  '/text-translator/': typeof TextTranslatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dev-tools/' | '/docx-translator/' | '/text-translator/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev-tools' | '/docx-translator' | '/text-translator'
  id:
    | '__root__'
    | '/'
    | '/dev-tools/'
    | '/docx-translator/'
    | '/text-translator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevToolsIndexRoute: typeof DevToolsIndexRoute
  DocxTranslatorIndexRoute: typeof DocxTranslatorIndexRoute
  TextTranslatorIndexRoute: typeof TextTranslatorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-translator/': {
      id: '/text-translator/'
      path: '/text-translator'
      fullPath: '/text-translator/'
      preLoaderRoute: typeof TextTranslatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docx-translator/': {
      id: '/docx-translator/'
      path: '/docx-translator'
      fullPath: '/docx-translator/'
      preLoaderRoute: typeof DocxTranslatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-tools/': {
      id: '/dev-tools/'
      path: '/dev-tools'
      fullPath: '/dev-tools/'
      preLoaderRoute: typeof DevToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevToolsIndexRoute: DevToolsIndexRoute,
  DocxTranslatorIndexRoute: DocxTranslatorIndexRoute,
  TextTranslatorIndexRoute: TextTranslatorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
